### ISSUE TITLE
Pass connectivity table from command line

### ISSUE THREAD

**Issue by Mahdisadjadi** [jaapkroe/polypy#3]
As the title says, this is a **feature request**. Instead of building a graph in the code using `connect_sparse(g, max_radius, pbc)`, a connectivity table (edge list/bond list) is passed from the command line, e.g:

`
polypy file.xyz connectivity.txt
` 

Then the graph is made based on that. This has applications in `percolation theory` and `geometrical graphs` (and of course amorphous systems) since a specific graph topology is considered. 

I am aware of two standards for connectivity files which either can be used:

1) _Bond list_: Each line consists of two numbers which are the end points of the bonds, e.g:
1 3
4 5
7 9
...

2) _Neighbor list_: Each line starts with the identifier of an atom and then lists its neighbors :
1 3 5 6 8
4 5 8 17
....

**Comment by jaapkroe** [comment]
Hi Mahdisadjadi,

Thanks for the feedback, it's a nice generalization indeed.
I attached a basic implementation. 
You can try it by supplying the command line option "--connect <filename>".
The file syntax is in the form of a neighbor list (with indices from 0 to n-1)
Would you care to try and see if works?

As a sidenote, the neighbor list format has the automatic advantage that you can make directed graphs.
However I am not entirely sure if all other algorithms directly generalize to this case.

Cheers,
Jaap

[polypy.zip](https://github.com/jaapkroe/polypy/files/323064/polypy.zip)

**Comment by Mahdisadjadi** [comment]
Hello @jaapkroe!

Your implementation works flawlessly (amazing work in general)! 

I agree that the neighbor list format is better especially in long-term maintenance and also most of the recent codes use it.

**Comment by jaapkroe** [comment]
Great, I'll close the thread then.
Thanks!
